# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language

en:
  languageCode: en-us
  contentDir: content/en
  title: Dmitry S. Kulyabov

ru:
  languageCode: ru-ru
  contentDir: content/ru
  title: Д. С. Кулябов
  params:
    description: Личный сайт Кулябова Дмитрия Сергевича
  menu:
    main:
      - name: Обо мне
        url: '/'
        weight: 10
      - name: Блог
        url: /#news
        weight: 15
      - name: Публикации
        url: /#papers
        weight: 20
      - name: Опыт
        url: experience/
        weight: 25
      - name: Проекты
        url: projects/
        weight: 30
      - name: Преподавание
        url: courses/
        weight: 50
      # - name: Контакты
      #   url: '#contact'
      #   weight: 60
